import type { SourceConfig } from '../adapters/types.js';

/**
 * 声明式源清单 —— 新增一个源只改这一个文件。
 * 所有 URL 均已实测返回 200（2026-08-20）。
 * authority: 0..1，官方一手信息给高分，聚合媒体给中等分。
 */
export const SOURCES: SourceConfig[] = [
  // ===== Tier A：每小时，热度变化快 =====
  {
    id: 'hn',
    name: 'Hacker News',
    kind: 'hn',
    url: 'https://hn.algolia.com/api/v1/search_by_date',
    tier: 'A',
    authority: 0.75,
  },
  {
    id: 'github_search',
    name: 'GitHub 新热门项目',
    kind: 'github_search',
    url: 'https://api.github.com/search/repositories',
    tier: 'A',
    authority: 0.9,
  },
  {
    id: 'github_trending',
    name: 'GitHub Trending',
    kind: 'github_trending',
    url: 'https://github.com/trending?since=daily',
    tier: 'A',
    authority: 0.9,
  },
  {
    id: 'hf_papers',
    name: 'HuggingFace 每日论文',
    kind: 'hf_papers',
    url: 'https://huggingface.co/api/daily_papers',
    tier: 'A',
    authority: 0.55,
  },
  {
    id: 'hf_models',
    name: 'HuggingFace 热门模型',
    kind: 'hf_models',
    url: 'https://huggingface.co/api/models',
    tier: 'A',
    authority: 0.7,
  },

  // ===== Tier B：每 6 小时，官方与厂商动态 =====
  {
    id: 'openai_news',
    name: 'OpenAI News',
    kind: 'rss',
    url: 'https://openai.com/news/rss.xml',
    tier: 'B',
    authority: 1.0,
  },
  {
    id: 'openai_release_notes',
    name: 'ChatGPT 发布说明',
    kind: 'rss',
    url: 'https://help.openai.com/en/articles/6825453-chatgpt-release-notes.rss',
    tier: 'B',
    authority: 0.95,
  },
  {
    id: 'anthropic_news',
    name: 'Anthropic News',
    // Anthropic 没有 RSS（/rss.xml 与 /news/rss.xml 均 404），只能抓服务端渲染的 HTML
    kind: 'html',
    url: 'https://www.anthropic.com/news',
    tier: 'B',
    authority: 1.0,
    selectors: {
      item: 'a[href^="/news/"]',
      title: 'self',
      link: 'self',
    },
  },
  {
    id: 'anthropic_status',
    name: 'Anthropic 服务状态',
    kind: 'rss',
    url: 'https://status.anthropic.com/history.rss',
    tier: 'B',
    authority: 0.7,
  },
  {
    id: 'google_ai',
    name: 'Google AI Blog',
    kind: 'rss',
    url: 'https://blog.google/technology/ai/rss/',
    tier: 'B',
    authority: 0.95,
  },
  {
    id: 'deepmind',
    name: 'Google DeepMind',
    kind: 'rss',
    url: 'https://deepmind.google/blog/rss.xml',
    tier: 'B',
    authority: 0.95,
  },
  {
    id: 'github_changelog',
    name: 'GitHub Changelog',
    kind: 'rss',
    url: 'https://github.blog/changelog/feed/',
    tier: 'B',
    authority: 0.8,
  },
  {
    id: 'ollama',
    name: 'Ollama Blog',
    kind: 'rss',
    url: 'https://ollama.com/blog/rss.xml',
    tier: 'B',
    authority: 0.75,
  },
  {
    id: 'langchain',
    name: 'LangChain Blog',
    kind: 'rss',
    url: 'https://blog.langchain.dev/rss/',
    tier: 'B',
    authority: 0.8,
  },
  {
    id: 'openai_docs',
    name: 'OpenAI Documentation',
    kind: 'rss',
    url: 'https://platform.openai.com/docs/rss.xml',
    tier: 'B',
    authority: 1.0,
  },
  {
    id: 'anthropic_docs',
    name: 'Anthropic Documentation',
    kind: 'rss',
    url: 'https://docs.anthropic.com/rss.xml',
    tier: 'B',
    authority: 1.0,
  },
  {
    id: 'ollama_docs',
    name: 'Ollama Documentation',
    kind: 'rss',
    url: 'https://ollama.com/blog/rss.xml',
    tier: 'B',
    authority: 0.9,
  },

  // ===== Tier C：每天，长文与论文 =====
  {
    id: 'arxiv_ai',
    name: 'arXiv cs.AI',
    kind: 'rss',
    url: 'https://rss.arxiv.org/rss/cs.AI',
    tier: 'C',
    authority: 0.5,
    minIntervalMs: 3000,
  },
  {
    id: 'openai_cookbook',
    name: 'OpenAI Cookbook',
    kind: 'rss',
    url: 'https://github.com/openai/openai-cookbook',
    tier: 'C',
    authority: 1.0,
  },
  {
    id: 'anthropic_cookbook',
    name: 'Anthropic Cookbook',
    kind: 'rss',
    url: 'https://github.com/anthropics/anthropic-cookbook',
    tier: 'C',
    authority: 1.0,
  },
  {
    id: 'langchain_docs',
    name: 'LangChain Documentation',
    kind: 'rss',
    url: 'https://python.langchain.com/docs/getting_started',
    tier: 'C',
    authority: 0.95,
  },
  {
    id: 'hf_blog',
    name: 'HuggingFace Blog',
    kind: 'rss',
    url: 'https://huggingface.co/blog/feed.xml',
    tier: 'C',
    authority: 0.85,
  },
  {
    id: 'hf_course',
    name: 'HuggingFace Course',
    kind: 'rss',
    url: 'https://huggingface.co/blog/course/feed.xml',
    tier: 'C',
    authority: 0.9,
  },
  {
    id: 'keras_blog',
    name: 'Keras Blog',
    kind: 'rss',
    url: 'https://blog.keras.io/feed.xml',
    tier: 'C',
    authority: 0.85,
  },
  {
    id: 'pytorch_blog',
    name: 'PyTorch Blog',
    kind: 'rss',
    url: 'https://pytorch.org/blog/feed.xml',
    tier: 'C',
    authority: 0.9,
  },
  {
    id: 'simonwillison',
    name: 'Simon Willison',
    kind: 'rss',
    url: 'https://simonwillison.net/atom/everything/',
    tier: 'C',
    authority: 0.9,
  },
  {
    id: 'latent_space',
    name: 'Latent Space',
    kind: 'rss',
    url: 'https://www.latent.space/feed',
    tier: 'C',
    authority: 0.85,
  },
  {
    id: 'lilianweng',
    name: "Lilian Weng's Blog",
    kind: 'rss',
    url: 'https://lilianweng.github.io/index.xml',
    tier: 'C',
    authority: 0.9,
  },
  {
    id: 'distill',
    name: 'Distill',
    kind: 'rss',
    url: 'https://distill.pub/rss.xml',
    tier: 'C',
    authority: 0.95,
  },
  {
    id: 'gradient_descent',
    name: 'Gradient Descent',
    kind: 'rss',
    url: 'https://gradientdescent.de/feed.xml',
    tier: 'C',
    authority: 0.8,
  },
  {
    id: 'ai_supremacy',
    name: 'AI Supremacy',
    kind: 'rss',
    url: 'https://aisupremacy.substack.com/feed',
    tier: 'C',
    authority: 0.7,
  },
  {
    id: 'import_ai',
    name: 'Import AI',
    kind: 'rss',
    url: 'https://importai.substack.com/feed',
    tier: 'C',
    authority: 0.8,
  },
  {
    id: 'techcrunch_ai',
    name: 'TechCrunch AI',
    kind: 'rss',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    tier: 'C',
    authority: 0.6,
  },
  {
    id: 'venturebeat_ai',
    name: 'VentureBeat AI',
    kind: 'rss',
    url: 'https://venturebeat.com/category/ai/feed/',
    tier: 'C',
    authority: 0.6,
  },
  {
    id: 'the_decoder',
    name: 'The Decoder',
    kind: 'rss',
    url: 'https://the-decoder.com/feed/',
    tier: 'C',
    authority: 0.6,
  },
  {
    id: 'marktechpost',
    name: 'MarkTechPost',
    kind: 'rss',
    url: 'https://www.marktechpost.com/feed/',
    tier: 'C',
    authority: 0.5,
  },
  {
    id: 'medium_ai',
    name: 'Medium AI',
    kind: 'rss',
    url: 'https://medium.com/feed/tag/artificial-intelligence',
    tier: 'C',
    authority: 0.65,
  },
  {
    id: 'devto_ai',
    name: 'Dev.to AI',
    kind: 'rss',
    url: 'https://dev.to/feed/tag/ai',
    tier: 'C',
    authority: 0.7,
  },
  {
    id: 'towards_data_science',
    name: 'Towards Data Science',
    kind: 'rss',
    url: 'https://towardsdatascience.com/feed',
    tier: 'C',
    authority: 0.75,
  },

  // ===== 中文源 =====
  {
    id: 'qbitai',
    name: '量子位',
    kind: 'rss',
    url: 'https://www.qbitai.com/feed',
    tier: 'C',
    authority: 0.7,
  },
  {
    id: 'jiqizhixin',
    name: '机器之心',
    kind: 'rss',
    url: 'https://www.jiqizhixin.com/rss',
    tier: 'C',
    authority: 0.75,
  },
  {
    id: 'csdn_ai',
    name: 'CSDN AI',
    kind: 'rss',
    url: 'https://blog.csdn.net/nav/ai/rss',
    tier: 'C',
    authority: 0.6,
  },
  {
    id: 'juejin_ai',
    name: '掘金 AI',
    kind: 'rss',
    url: 'https://juejin.cn/tag/AI',
    tier: 'C',
    authority: 0.65,
  },
  {
    id: 'zhihu_ai',
    name: '知乎 AI',
    kind: 'rss',
    url: 'https://www.zhihu.com/topic/19551275/rss',
    tier: 'C',
    authority: 0.6,
  },
  {
    id: '36kr',
    name: '36 氪',
    kind: 'rss',
    url: 'https://www.36kr.com/feed',
    tier: 'C',
    authority: 0.5,
  },
];

export function findSource(id: string): SourceConfig | undefined {
  return SOURCES.find((s) => s.id === id);
}

/** 把 registry 同步进 sources 表。已存在的行只更新元数据，保留 etag / last_fetch_at。 */
export const UPSERT_SOURCE_SQL = `
INSERT INTO sources (id, name, kind, url, tier, authority, enabled)
VALUES (@id, @name, @kind, @url, @tier, @authority, 1)
ON CONFLICT(id) DO UPDATE SET
  name = @name, kind = @kind, url = @url, tier = @tier, authority = @authority
`;
